### ISSUE TITLE
Hostname ?

### ISSUE THREAD

**Issue by Nasjoe** [hauptmedia/docker-mariadb#1]
Hi

Thx for your job, i search a similar solution.
Just two questions.

When i add a --name node1 to the run command, the process shut down : 

"
mysqld: Too many arguments (first extra is '172.17.0.242').
2015-10-22 20:11:05 139915705542592 [ERROR] Aborting

Error in my_thread_global_end(): 1 threads didn't exit
"

And, how can i know the ip adress of the node too ad within "CLUSTER_ADDRESS=gcomm://" if the node ar not started ? 
Actualy, i add a "-h node1" to the run command, but it seem strange.

Thanks you !

**Comment by hauptmedia** [comment]
Hi can you send me the complete docker run command?

**Comment by Nasjoe** [comment]
Hi !
Thanks for you reply.

It's the docker run command i use to try to launch the master : 

docker run -i -t --rm \
--name node1 \
-h node1 \
-e TIMEZONE=Europe/Paris \
-e MYSQL_ROOT_PASSWORD=test \
-e REPLICATION_PASSWORD=test \
-e GALERA=On \
-e NODE_NAME=node1 \
-e CLUSTER_NAME=test \
-e CLUSTER_ADDRESS=gcomm://node1,node2,node3 \
hauptmedia/mariadb:10.1 --wsrep-new-cluster

here the result : 
http://paste.ubuntu.com/12915616/

Thanks !
